export const KAFALA_FLOW_COPY = {
  ar: {
    steps: ['الخطوة 1 من 4 — تسجيل الدخول', 'الخطوة 2 من 4 — اختيار خطة الكفالة', 'الخطوة 3 من 4 — طريقة الدفع', 'الخطوة 4 من 4 — مراجعة وتأكيد'],
    loading: 'جاري التحميل...', notFound: 'الكفالة غير موجودة', alreadySponsored: 'هذا اليتيم مكفول بالفعل. الرجاء اختيار يتيم آخر.', backList: 'العودة للقائمة', complete: 'إتمام الكفالة', year: 'سنة', perMonth: 'درهم/شهر', changeOption: 'تغيير الخيار', signIn: 'تسجيل الدخول', createAccount: 'إنشاء حساب', signInHelp: 'أدخل رقم هاتفك وكلمة المرور', registerHelp: 'انضم إلى مجتمع الكافلين', enterCode: 'أدخل رمز التحقق', resendAfter: 'إعادة الإرسال بعد', resend: 'إعادة إرسال الرمز', name: 'الاسم *', namePlaceholder: 'الاسم', email: 'البريد *', phone: 'رقم الهاتف *', password: 'كلمة المرور *', confirm: 'تأكيد كلمة المرور *', secure: 'بياناتك محمية بتشفير آمن', continueQuestion: 'كيف تريد المتابعة؟', continueHelp: 'سجّل دخولك لمتابعة كفالاتك', fastest: 'الأسرع', free: 'مجاني',
    planTitle: 'اختر خطة الكفالة', planHelp: 'الكفالة الشهرية تُجدَّد تلقائياً — يمكنك الإيقاف في أي وقت', monthlyPlan: 'كفالة شهرية', monthlyDesc: 'تجديد تلقائي كل شهر', mostChosen: 'الأكثر اختياراً', annualPlan: 'كفالة سنوية', annualDesc: 'ادفع مرة واحدة ووفّر 10%', saving: (amount) => `توفير ${amount} درهم`, perYear: 'درهم/سنة', coversTitle: 'كفالتك الشهرية ستغطي:', covers: (name) => ['كتب ولوازم مدرسية كاملة', 'وجبات يومية صحية', 'رعاية صحية شهرية', `تقرير ربع سنوي عن أحوال ${name}`], paymentNote: 'يمكنك الدفع بتحويل بنكي شهري أو بطاقة بنكية. ستُرسَل لك تذكيرات على واتساب قبل كل تجديد.',
    paymentTitle: 'طريقة الدفع', paymentHelp: 'اختر الطريقة المناسبة لك', card: 'بطاقة بنكية', cardHelp: 'Visa، Mastercard — اشتراك تلقائي شهري', cardNote: 'ستُوجَّه إلى صفحة دفع آمنة عبر Whop. يتجدد الاشتراك تلقائياً كل شهر ويمكنك الإلغاء في أي وقت.', transfer: 'تحويل بنكي أو وكالة', transferHelp: 'بنك · Wafacash · Cash Plus', bankDetails: 'بيانات الحساب البنكي', accountHolder: 'صاحب الحساب', rib: 'رقم الحساب (RIB)', copied: 'تم نسخ الرقم', copyRib: 'نسخ رقم الحساب', bankTransfer: 'تحويل بنكي', cashAgency: 'وكالة نقد', uploadReceipt: 'رفع وصل الدفع', attachReceipt: 'أرفق وصل الدفع *', referenceOptional: 'رقم المرجع (اختياري)', referencePlaceholder: 'رقم الوصل من البنك', cashHelp: 'حوّل المبلغ عبر أي وكالة نقد (Wafacash، Cash Plus...) ثم ارفع وصل الدفع أدناه.', receiptReference: 'رقم الوصل / المرجع', receiptPlaceholder: 'أدخل رقم الوصل من الوكالة',
    reviewTitle: 'مراجعة التفاصيل', reviewHelp: 'تأكد من صحة التفاصيل', total: 'إجمالي الكفالة الشهرية', monthly: 'كفالة شهرية', annual: 'كفالة سنوية', monthlyAmount: 'المبلغ الشهري', paymentMethod: 'طريقة الدفع', donor: 'المتبرع', anonymous: 'التبرع باسم مجهول', anonymousName: 'مجهول الهوية', finalTrust: 'بياناتك محمية · يمكنك الإلغاء في أي وقت · جمعية معتمدة رسمياً', nextReview: 'التالي: مراجعة التفاصيل →', sponsor: (female, price) => `اكفل${female ? 'ها' : 'ه'} — ${price} درهم/شهر`, verify: 'تحقق من الرمز', submitRequest: 'إرسال طلب الكفالة', paying: 'جاري التحويل...', sending: 'جاري الإرسال...', payCard: 'الدفع بالبطاقة', noCommitment: 'بدون التزام طويل المدى · إلغاء مجاني في أي وقت',
    pendingTitle: 'تم إرسال طلب الكفالة بنجاح', successTitle: 'تم تسجيل كفالتك!', pendingBody: 'طلبك قيد المراجعة من الفريق. سيصلك إشعار واتساب عند التأكيد.', successBody: 'جزاك الله خيراً على هذا العمل الصالح. ستتلقى رسالة تأكيد عبر واتساب.', backHome: 'العودة للرئيسية',
    resendFailed: 'تعذر إعادة الإرسال', codeSent: 'تم إرسال الرمز', phoneInvalid: 'رقم هاتف غير صحيح', passwordRequired: 'كلمة المرور مطلوبة', loginDone: 'تم تسجيل الدخول', unverified: 'حسابك غير مفعّل. تم إرسال رمز التحقق مجدداً.', loginFailed: 'فشل تسجيل الدخول', connectionError: 'خطأ في الاتصال', nameRequired: 'الاسم مطلوب', emailInvalid: 'بريد غير صحيح', passwordLength: '6 أحرف على الأقل', passwordMismatch: 'كلمات المرور غير متطابقة', registrationError: 'خطأ في التسجيل', accountCreated: 'تم إنشاء الحساب', verificationError: 'خطأ في التحقق', signInFirst: 'يرجى تسجيل الدخول أولاً', receiptRequired: 'يجب إرفاق وصل الدفع أو إدخال رقم المرجع', genericError: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
  },
  fr: {
    steps: ['Étape 1 sur 4 — Connexion', 'Étape 2 sur 4 — Formule de kafala', 'Étape 3 sur 4 — Paiement', 'Étape 4 sur 4 — Vérification'],
    loading: 'Chargement...', notFound: 'Kafala introuvable', alreadySponsored: 'Cet enfant est déjà parrainé. Choisissez un autre profil.', backList: 'Retour à la liste', complete: 'Finaliser la kafala', year: 'ans', perMonth: 'MAD/mois', changeOption: 'Changer d’option', signIn: 'Se connecter', createAccount: 'Créer un compte', signInHelp: 'Saisissez votre téléphone et votre mot de passe', registerHelp: 'Rejoignez la communauté des parrains', enterCode: 'Saisissez le code de vérification', resendAfter: 'Renvoyer dans', resend: 'Renvoyer le code', name: 'Nom *', namePlaceholder: 'Nom', email: 'E-mail *', phone: 'Téléphone *', password: 'Mot de passe *', confirm: 'Confirmer le mot de passe *', secure: 'Vos données sont protégées', continueQuestion: 'Comment souhaitez-vous continuer ?', continueHelp: 'Connectez-vous pour suivre vos kafalas', fastest: 'Le plus rapide', free: 'Gratuit',
    planTitle: 'Choisissez une formule', planHelp: 'La kafala mensuelle est renouvelée automatiquement — annulation possible à tout moment', monthlyPlan: 'Kafala mensuelle', monthlyDesc: 'Renouvellement mensuel automatique', mostChosen: 'La plus choisie', annualPlan: 'Kafala annuelle', annualDesc: 'Payez une fois et économisez 10 %', saving: (amount) => `Économie de ${amount} MAD`, perYear: 'MAD/an', coversTitle: 'Votre kafala mensuelle couvre :', covers: (name) => ['Livres et fournitures scolaires', 'Repas quotidiens équilibrés', 'Suivi médical mensuel', `Rapport trimestriel sur ${name}`], paymentNote: 'Payez par virement mensuel ou carte. Vous recevrez des rappels WhatsApp avant chaque renouvellement.',
    paymentTitle: 'Mode de paiement', paymentHelp: 'Choisissez le mode qui vous convient', card: 'Carte bancaire', cardHelp: 'Visa, Mastercard — abonnement mensuel automatique', cardNote: 'Vous serez redirigé vers une page Whop sécurisée. Vous pouvez annuler à tout moment.', transfer: 'Virement bancaire ou agence', transferHelp: 'Banque · Wafacash · Cash Plus', bankDetails: 'Coordonnées bancaires', accountHolder: 'Titulaire du compte', rib: 'Numéro de compte (RIB)', copied: 'Numéro copié', copyRib: 'Copier le RIB', bankTransfer: 'Virement bancaire', cashAgency: 'Agence de transfert', uploadReceipt: 'Téléverser le reçu', attachReceipt: 'Joindre le reçu *', referenceOptional: 'Référence (facultatif)', referencePlaceholder: 'Référence bancaire', cashHelp: 'Envoyez le montant via Wafacash ou Cash Plus, puis joignez le reçu ci-dessous.', receiptReference: 'Numéro du reçu / référence', receiptPlaceholder: 'Référence de l’agence',
    reviewTitle: 'Vérifiez les informations', reviewHelp: 'Confirmez les détails avant l’envoi', total: 'Total mensuel de la kafala', monthly: 'Kafala mensuelle', annual: 'Kafala annuelle', monthlyAmount: 'Montant mensuel', paymentMethod: 'Mode de paiement', donor: 'Donateur', anonymous: 'Faire un don anonyme', anonymousName: 'Anonyme', finalTrust: 'Données protégées · Annulation à tout moment · Association agréée', nextReview: 'Suivant : vérification →', sponsor: (_female, price) => `Parrainer — ${price} MAD/mois`, verify: 'Vérifier le code', submitRequest: 'Envoyer la demande', paying: 'Redirection...', sending: 'Envoi...', payCard: 'Payer par carte', noCommitment: 'Sans engagement à long terme · Annulation gratuite', pendingTitle: 'Demande de kafala envoyée', successTitle: 'Votre kafala est enregistrée !', pendingBody: 'Votre demande est en cours de vérification. Vous recevrez une confirmation sur WhatsApp.', successBody: 'Merci pour ce geste généreux. Vous recevrez une confirmation sur WhatsApp.', backHome: 'Retour à l’accueil', resendFailed: 'Impossible de renvoyer le code', codeSent: 'Code envoyé', phoneInvalid: 'Numéro invalide', passwordRequired: 'Mot de passe requis', loginDone: 'Connexion réussie', unverified: 'Compte non activé. Un nouveau code a été envoyé.', loginFailed: 'Échec de la connexion', connectionError: 'Erreur de connexion', nameRequired: 'Nom requis', emailInvalid: 'E-mail invalide', passwordLength: '6 caractères minimum', passwordMismatch: 'Les mots de passe ne correspondent pas', registrationError: 'Échec de l’inscription', accountCreated: 'Compte créé', verificationError: 'Échec de la vérification', signInFirst: 'Connectez-vous d’abord', receiptRequired: 'Ajoutez un reçu ou une référence', genericError: 'Une erreur est survenue. Réessayez.',
  },
  en: {
    steps: ['Step 1 of 4 — Sign in', 'Step 2 of 4 — Sponsorship plan', 'Step 3 of 4 — Payment', 'Step 4 of 4 — Review'],
    loading: 'Loading...', notFound: 'Sponsorship not found', alreadySponsored: 'This child is already sponsored. Please choose another profile.', backList: 'Back to list', complete: 'Complete sponsorship', year: 'years old', perMonth: 'MAD/month', changeOption: 'Change option', signIn: 'Sign in', createAccount: 'Create account', signInHelp: 'Enter your phone number and password', registerHelp: 'Join our sponsor community', enterCode: 'Enter the verification code', resendAfter: 'Resend in', resend: 'Resend code', name: 'Name *', namePlaceholder: 'Name', email: 'Email *', phone: 'Phone number *', password: 'Password *', confirm: 'Confirm password *', secure: 'Your data is securely encrypted', continueQuestion: 'How would you like to continue?', continueHelp: 'Sign in to track your sponsorships', fastest: 'Fastest', free: 'Free',
    planTitle: 'Choose a sponsorship plan', planHelp: 'Monthly sponsorship renews automatically — cancel at any time', monthlyPlan: 'Monthly sponsorship', monthlyDesc: 'Automatically renews each month', mostChosen: 'Most popular', annualPlan: 'Annual sponsorship', annualDesc: 'Pay once and save 10%', saving: (amount) => `Save ${amount} MAD`, perYear: 'MAD/year', coversTitle: 'Your monthly sponsorship covers:', covers: (name) => ['School books and supplies', 'Healthy daily meals', 'Monthly healthcare', `Quarterly update about ${name}`], paymentNote: 'Pay by monthly bank transfer or card. We will send WhatsApp reminders before each renewal.',
    paymentTitle: 'Payment method', paymentHelp: 'Choose the method that works for you', card: 'Bank card', cardHelp: 'Visa, Mastercard — automatic monthly subscription', cardNote: 'You will be redirected to a secure Whop checkout. You can cancel at any time.', transfer: 'Bank transfer or cash agency', transferHelp: 'Bank · Wafacash · Cash Plus', bankDetails: 'Bank account details', accountHolder: 'Account holder', rib: 'Account number (RIB)', copied: 'Number copied', copyRib: 'Copy account number', bankTransfer: 'Bank transfer', cashAgency: 'Cash agency', uploadReceipt: 'Upload payment receipt', attachReceipt: 'Attach payment receipt *', referenceOptional: 'Reference (optional)', referencePlaceholder: 'Bank receipt reference', cashHelp: 'Send the amount through Wafacash or Cash Plus, then upload the receipt below.', receiptReference: 'Receipt number / reference', receiptPlaceholder: 'Agency receipt reference',
    reviewTitle: 'Review details', reviewHelp: 'Confirm everything before submitting', total: 'Monthly sponsorship total', monthly: 'Monthly sponsorship', annual: 'Annual sponsorship', monthlyAmount: 'Monthly amount', paymentMethod: 'Payment method', donor: 'Donor', anonymous: 'Donate anonymously', anonymousName: 'Anonymous', finalTrust: 'Data protected · Cancel at any time · Accredited association', nextReview: 'Next: review →', sponsor: (_female, price) => `Sponsor — ${price} MAD/month`, verify: 'Verify code', submitRequest: 'Send sponsorship request', paying: 'Redirecting...', sending: 'Sending...', payCard: 'Pay by card', noCommitment: 'No long-term commitment · Cancel free at any time', pendingTitle: 'Sponsorship request sent', successTitle: 'Your sponsorship is registered!', pendingBody: 'Your request is under review. We will confirm it through WhatsApp.', successBody: 'Thank you for this generous act. You will receive confirmation through WhatsApp.', backHome: 'Back to home', resendFailed: 'Unable to resend code', codeSent: 'Code sent', phoneInvalid: 'Invalid phone number', passwordRequired: 'Password is required', loginDone: 'Signed in', unverified: 'Your account is not active. A new verification code was sent.', loginFailed: 'Sign-in failed', connectionError: 'Connection error', nameRequired: 'Name is required', emailInvalid: 'Invalid email', passwordLength: 'At least 6 characters', passwordMismatch: 'Passwords do not match', registrationError: 'Registration failed', accountCreated: 'Account created', verificationError: 'Verification failed', signInFirst: 'Please sign in first', receiptRequired: 'Attach a receipt or enter a reference', genericError: 'Something went wrong. Please try again.',
  },
};

export const getKafalaFlowCopy = (language) => KAFALA_FLOW_COPY[language] || KAFALA_FLOW_COPY.ar;
