import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from 'convex/react';
import { api } from '../../../../convex/_generated/api';
import { useApp } from '../../../context/AppContext';
import { convexFileUrl } from '../../../lib/convex';
import KafalaAvatar from '../../../components/kafala/KafalaAvatar';

const COPY = {
  ar: { badge: 'برنامج الكفالة', title: 'اكفل يتيماً وغيّر حياته', subtitle: 'بكفالتك الشهرية، تمنح طفلاً يتيماً التعليم والغذاء والرعاية الصحية التي يستحقها.', start: 'ابدأ الكفالة الآن', all: 'الكل', available: 'متاح للكفالة', sponsored: 'مكفول', sponsoredCount: 'يتيم تحت الرعاية', availableCount: 'متاح للكفالة', monthly: 'شهرياً', listing: 'الأيتام المتاحون للكفالة', loading: 'جاري التحميل...', empty: 'لا توجد كفالات مطابقة حالياً', age: 'سنة', location: 'الموقع', perMonth: 'درهم / شهر', already: 'مكفول بالفعل', sponsor: 'اكفله الآن', sponsorFemale: 'اكفليها الآن', why: 'لماذا الكفالة؟', whyBody: 'توفّر كفالتك الشهرية للطفل التعليم والغذاء والرعاية الصحية والملابس.', discover: 'اكتشف الكفالات المتاحة' },
  fr: { badge: 'PROGRAMME KAFALA', title: 'Parrainez un orphelin, changez sa vie', subtitle: 'Votre parrainage mensuel offre à un enfant l’éducation, l’alimentation et les soins de santé qu’il mérite.', start: 'Parrainer maintenant', all: 'Tous', available: 'Disponible', sponsored: 'Parrainé', sponsoredCount: 'enfants accompagnés', availableCount: 'disponibles', monthly: 'par mois', listing: 'Enfants disponibles au parrainage', loading: 'Chargement...', empty: 'Aucun parrainage correspondant pour le moment', age: 'ans', location: 'Lieu', perMonth: 'MAD / mois', already: 'Déjà parrainé', sponsor: 'Parrainer maintenant', sponsorFemale: 'Parrainer maintenant', why: 'Pourquoi la Kafala ?', whyBody: 'Votre soutien mensuel couvre l’éducation, l’alimentation, les soins de santé et les vêtements de l’enfant.', discover: 'Découvrir les parrainages disponibles' },
  en: { badge: 'KAFALA PROGRAM', title: 'Sponsor an orphan and change a life', subtitle: 'Your monthly sponsorship gives a child the education, food, and healthcare they deserve.', start: 'Sponsor now', all: 'All', available: 'Available', sponsored: 'Sponsored', sponsoredCount: 'children supported', availableCount: 'available', monthly: 'per month', listing: 'Children available for sponsorship', loading: 'Loading...', empty: 'No matching sponsorships at the moment', age: 'years old', location: 'Location', perMonth: 'MAD / month', already: 'Already sponsored', sponsor: 'Sponsor now', sponsorFemale: 'Sponsor now', why: 'Why sponsor a child?', whyBody: 'Your monthly sponsorship provides education, food, healthcare, and clothing for a child.', discover: 'Discover available sponsorships' },
};

const useIsMobile = () => {
  const [isMobile, setIsMobile] = useState(window.innerWidth < 768);
  useEffect(() => { const update = () => setIsMobile(window.innerWidth < 768); window.addEventListener('resize', update); return () => window.removeEventListener('resize', update); }, []);
  return isMobile;
};

export default function KafalaList() {
  const { currentLanguage } = useApp();
  const lang = currentLanguage?.code || 'ar';
  const tx = COPY[lang] || COPY.ar;
  const locale = lang === 'ar' ? 'ar-MA' : lang === 'fr' ? 'fr-FR' : 'en-US';
  const isMobile = useIsMobile();
  const [filter, setFilter] = useState('all');
  const kafalaList = useQuery(api.kafala.getPublicKafalaList, {});
  const all = kafalaList || [];
  const availableCount = all.filter((item) => item.status === 'active').length;
  const sponsoredCount = all.filter((item) => item.status === 'sponsored').length;
  const filtered = all.filter((item) => filter === 'all' || (filter === 'available' ? item.status === 'active' : item.status === 'sponsored'));
  const getBio = (value) => typeof value === 'string' ? value : value?.[lang] || value?.ar || value?.fr || value?.en || '';

  if (kafalaList === undefined) return <div style={{ minHeight: '70vh', display: 'grid', placeItems: 'center', color: '#94a3b8', fontFamily: lang === 'ar' ? 'var(--font-arabic)' : 'Inter, sans-serif' }}>{tx.loading}</div>;

  return <div dir={currentLanguage?.dir || (lang === 'ar' ? 'rtl' : 'ltr')} style={{ minHeight: '100vh', background: '#f6f8f8', color: '#0e1a1b', fontFamily: lang === 'ar' ? 'var(--font-arabic)' : 'Inter, sans-serif' }}>
    <section style={{ background: 'linear-gradient(160deg,#3D2506,#6B4F12,#C4A882)', padding: isMobile ? '50px 18px' : '70px 28px', color: 'white', textAlign: 'center' }}>
      <div style={{ maxWidth: 720, margin: 'auto' }}><div style={{ color: '#F5EBD9', fontSize: 12, letterSpacing: '.15em', fontWeight: 900 }}>{tx.badge}</div><h1 style={{ fontSize: isMobile ? 33 : 46, lineHeight: 1.18, margin: '14px 0' }}>{tx.title}</h1><p style={{ maxWidth: 560, margin: '0 auto 28px', color: 'rgba(255,255,255,.84)', lineHeight: 1.8 }}>{tx.subtitle}</p><button type="button" onClick={() => setFilter('available')} style={{ height: 52, padding: '0 28px', border: 'none', borderRadius: 99, background: 'white', color: '#6B4F12', fontFamily: 'inherit', fontWeight: 900, cursor: 'pointer' }}>{tx.start}</button>
        <div style={{ display: 'flex', justifyContent: 'center', gap: isMobile ? 24 : 48, marginTop: 32, flexWrap: 'wrap' }}><div><b style={{ fontSize: 28 }}>{sponsoredCount}</b><div style={{ color: '#F5EBD9', fontSize: 12 }}>{tx.sponsoredCount}</div></div><div><b style={{ fontSize: 28 }}>{availableCount}</b><div style={{ color: '#F5EBD9', fontSize: 12 }}>{tx.availableCount}</div></div><div><b style={{ fontSize: 28 }}>300 MAD</b><div style={{ color: '#F5EBD9', fontSize: 12 }}>{tx.monthly}</div></div></div>
      </div>
    </section>
    <div style={{ background: 'white', borderBottom: '1px solid #E5E9EB', position: 'sticky', top: 64, zIndex: 10 }}><div style={{ maxWidth: 1200, margin: 'auto', padding: '13px 20px', display: 'flex', gap: 10, overflowX: 'auto' }}>{[['all', tx.all, all.length], ['available', tx.available, availableCount], ['sponsored', tx.sponsored, sponsoredCount]].map(([id, label, count]) => <button key={id} type="button" onClick={() => setFilter(id)} style={{ flex: '0 0 auto', height: 36, padding: '0 16px', borderRadius: 99, cursor: 'pointer', fontFamily: 'inherit', fontWeight: 800, border: `1.5px solid ${filter === id ? '#8B6914' : '#E5E9EB'}`, background: filter === id ? '#8B6914' : 'white', color: filter === id ? 'white' : '#64748b' }}>{label} ({count})</button>)}</div></div>
    <main style={{ maxWidth: 1200, margin: 'auto', padding: isMobile ? '26px 16px 56px' : '42px 28px 64px' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}><h2 style={{ margin: 0, fontSize: 22 }}>{tx.listing}</h2><span style={{ color: '#8B6914', fontWeight: 900 }}>{filtered.length}</span></div>
      {filtered.length === 0 ? <div style={{ padding: 64, textAlign: 'center', color: '#64748b', background: 'white', borderRadius: 18 }}>{tx.empty}</div> : <div style={{ display: 'grid', gridTemplateColumns: `repeat(auto-fill,minmax(${isMobile ? '150px' : '255px'},1fr))`, gap: isMobile ? 14 : 22 }}>{filtered.map((item) => { const sponsored = item.status === 'sponsored'; const photoUrl = convexFileUrl(item.photo) || item.photo; return <Link key={item._id} to={`/kafala/${item._id}`} style={{ color: 'inherit', textDecoration: 'none' }}><article style={{ height: '100%', background: 'white', border: '1px solid #E5E9EB', borderRadius: 18, overflow: 'hidden', boxShadow: '0 3px 10px rgba(0,0,0,.05)' }}><div style={{ padding: '22px 16px 16px', textAlign: 'center', background: 'linear-gradient(180deg,#F5EBD9,white)' }}><div style={{ width: 82, height: 82, margin: 'auto', borderRadius: '50%', overflow: 'hidden', background: '#E8D4B0' }}><KafalaAvatar gender={item.gender} photo={item.photo} photoUrl={photoUrl} size={82} /></div><h3 style={{ margin: '10px 0 3px', fontSize: 17 }}>{item.name}</h3><div style={{ fontSize: 13, color: '#8B6914' }}>{item.age} {tx.age}</div>{item.location && <div style={{ fontSize: 12, color: '#64748b', marginTop: 5 }}><span className="material-symbols-outlined no-flip" style={{ fontSize: 14, verticalAlign: 'middle' }}>location_on</span> {item.location}</div>}<span style={{ display: 'inline-block', marginTop: 9, padding: '4px 9px', borderRadius: 99, fontSize: 11, fontWeight: 900, background: sponsored ? '#F5EBD9' : '#DCFCE7', color: sponsored ? '#8B6914' : '#15803D' }}>{sponsored ? tx.sponsored : tx.available}</span></div><div style={{ padding: 16 }}>{getBio(item.bio) && <p style={{ minHeight: 42, margin: '0 0 12px', color: '#64748b', fontSize: 12, lineHeight: 1.65, overflow: 'hidden' }}>{getBio(item.bio)}</p>}<div style={{ color: '#8B6914', textAlign: 'center', fontWeight: 900, fontSize: 19, marginBottom: 12 }}>{Number(item.monthlyPrice || 300).toLocaleString(locale)} <small style={{ color: '#64748b', fontWeight: 600 }}>{tx.perMonth}</small></div><div style={{ height: 42, display: 'grid', placeItems: 'center', borderRadius: 10, background: sponsored ? '#F5EBD9' : '#8B6914', color: sponsored ? '#8B6914' : 'white', fontWeight: 900, fontSize: 13 }}>{sponsored ? tx.already : item.gender === 'female' ? tx.sponsorFemale : tx.sponsor}</div></div></article></Link>; })}</div>}
      <section style={{ marginTop: 42, background: 'linear-gradient(135deg,#3D2506,#6B4F12)', borderRadius: 20, padding: isMobile ? 26 : 38, color: 'white', textAlign: 'center' }}><h2 style={{ margin: '0 0 10px' }}>{tx.why}</h2><p style={{ maxWidth: 600, margin: '0 auto 20px', lineHeight: 1.7, color: '#F5EBD9' }}>{tx.whyBody}</p><button type="button" onClick={() => setFilter('available')} style={{ border: 'none', borderRadius: 99, background: 'white', color: '#6B4F12', cursor: 'pointer', fontFamily: 'inherit', fontWeight: 900, padding: '12px 20px' }}>{tx.discover}</button></section>
    </main>
  </div>;
}
